### ISSUE TITLE
Database Firebase

### ISSUE THREAD

**Issue by Derewith** [datwheat/pul#1]
Can u please send us the database to make it working?

**Comment by datwheat** [comment]
You can try it on iOS and Android here https://play.google.com/store/apps/details?id=io.github.datwheat.pul&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1 https://itunes.apple.com/us/app/p%C3%BCl-carpooling-for-students-by-students/id1196047562?ls=1&mt=8

**Comment by Derewith** [comment]
@datwheat yeah but if u place it to github you shoul add also the database just to let us try it out with other school no?

**Comment by datwheat** [comment]
No I shouldn't. But if you're clever enough you can find out the database structure by reading the code! 👍
